insert into services (id, name, image, restart, command , container_name , build , hostname , mem_limit , memswap_limit , useEnvironments, usePorts, useRestart, useVolumes, useExpose , useNetworks, useDependsOn, useCommand , useContainerName, useBuild , useMemLimit , useMemswapLimit , useHostname, useImage)
values (1, 'postgres', 'postgres:9.6.8', null,  null, null, false, true, false,true,true, false,  false, false, false, false, false, false, false, false, false, false, false, true);
insert into services (id, name, image, restart, command , container_name , build , hostname , mem_limit , memswap_limit , useEnvironments, usePorts, useRestart, useVolumes, useExpose , useNetworks, useDependsOn, useCommand , useContainerName, useBuild , useMemLimit , useMemswapLimit , useHostname, useImage)
values (2, 'mongoDB', 'mongo', 'always', null, null, null, null, null, null, true, true, true, true, false, false, false, false, false, false, false, false, false, true);
insert into services (id, name, image, restart, command , container_name , build , hostname , mem_limit , memswap_limit , useEnvironments, usePorts, useRestart, useVolumes, useExpose , useNetworks, useDependsOn, useCommand , useContainerName, useBuild , useMemLimit , useMemswapLimit , useHostname, useImage)
values (3, 'mongo express', 'mongo-express', 'always', null, null, null, null, null, null, true, true, true, false, false, false, false, false, false, false, false, false, false, true);
insert into services (id, name, image, restart, command , container_name , build , hostname , mem_limit , memswap_limit , useEnvironments, usePorts, useRestart, useVolumes, useExpose , useNetworks, useDependsOn, useCommand , useContainerName, useBuild , useMemLimit , useMemswapLimit , useHostname, useImage)
values (4, 'apache', 'httpd:2.4', null, null, null, null, null, null, null, false, true,  false, true, true, false, false, false, false, false, false, false, false, true);
insert into services (id, name, image, restart, command , container_name , build , hostname , mem_limit , memswap_limit , useEnvironments, usePorts, useRestart, useVolumes, useExpose , useNetworks, useDependsOn, useCommand , useContainerName, useBuild , useMemLimit , useMemswapLimit , useHostname, useImage)
values (5, 'nginx', 'nginx:1.13', null, null, null, null, null, null, null, false, true,  false, false, true, false, true, false, false, false, false, false, false, true);
insert into services (id, name, image, restart, command , container_name , build , hostname , mem_limit , memswap_limit , useEnvironments, usePorts, useRestart, useVolumes, useExpose , useNetworks, useDependsOn, useCommand , useContainerName, useBuild , useMemLimit , useMemswapLimit , useHostname, useImage)
values (6, 'oracle', 'quay.io/maksymbilenko/oracle-xe-11g', null, null, null, null, null, null, null, false, true,  false, false, false, false, false, false, false, false, false, false, false, true);
insert into services (id, name, image, restart, command , container_name , build , hostname , mem_limit , memswap_limit , useEnvironments, usePorts, useRestart, useVolumes, useExpose , useNetworks, useDependsOn, useCommand , useContainerName, useBuild , useMemLimit , useMemswapLimit , useHostname, useImage)
values (7, 'rabbitMQ', 'rabbitmq:management', null, null, null, null, null, null, null, false, true,  false, false, false, false, false, false, false, false, false, false, false, true);
insert into services (id, name, image, restart, command , container_name , build , hostname , mem_limit , memswap_limit , useEnvironments, usePorts, useRestart, useVolumes, useExpose , useNetworks, useDependsOn, useCommand , useContainerName, useBuild , useMemLimit , useMemswapLimit , useHostname, useImage)
values (8, 'elasticsearch', 'docker.elastic.co/elasticsearch/elasticsearch:7.4.0', null, null, 'elasticsearch', null, null, null, null, true, true,  false, false, true, true, false, false, true, false, false, false, false, true);
insert into services (id, name, image, restart, command , container_name , build , hostname , mem_limit , memswap_limit , useEnvironments, usePorts, useRestart, useVolumes, useExpose , useNetworks, useDependsOn, useCommand , useContainerName, useBuild , useMemLimit , useMemswapLimit , useHostname, useImage)
values (9, 'kibana', 'docker.elastic.co/kibana/kibana:7.4.2', null, null, 'kibana', null, null, null, null, false, true,  false, true, false, true, true, false, true, false, false, false, false, true);
insert into services (id, name, image, restart, command , container_name , build , hostname , mem_limit , memswap_limit , useEnvironments, usePorts, useRestart, useVolumes, useExpose , useNetworks, useDependsOn, useCommand , useContainerName, useBuild , useMemLimit , useMemswapLimit , useHostname, useImage)
values (10, 'h2', '1000kit/h2', null, null, 'h2', null, 'h2', null, null, false, true, false, false, false, false, false, false, true, false, false, false, true , true);
insert into services (id, name, image, restart, command , container_name , build , hostname , mem_limit , memswap_limit , useEnvironments, usePorts, useRestart, useVolumes, useExpose , useNetworks, useDependsOn, useCommand , useContainerName, useBuild , useMemLimit , useMemswapLimit , useHostname, useImage)
values (11, 'zookeeper', 'wurstmeister/zookeeper', null, null, null, null, 'zookeeper', null, null, false, true, false, false, false, false, false, false, false, false, false, false, true, true);
insert into services (id, name, image, restart, command , container_name , build , hostname , mem_limit , memswap_limit , useEnvironments, usePorts, useRestart, useVolumes, useExpose , useNetworks, useDependsOn, useCommand , useContainerName, useBuild , useMemLimit , useMemswapLimit , useHostname, useImage)
values (12, 'kafka', 'wurstmeister/kafka', null, '[start-kafka.sh]', null, null, 'kafka', null, null, true, true, false, true, false, false, true, true, false, false, false, false, true, true);
insert into services (id, name, image, restart, command , container_name , build , hostname , mem_limit , memswap_limit , useEnvironments, usePorts, useRestart, useVolumes, useExpose , useNetworks, useDependsOn, useCommand , useContainerName, useBuild , useMemLimit , useMemswapLimit , useHostname, useImage)
values (13, 'cassandra', null, null, null, null, './docker-data/cassandra', 'cassandra-01', null, null, false, true, false, false, false, true, false, false, false, true, false, false, true, false );